apiVersion: cluster.x-k8s.io.mydomain.com/v1
kind: Machine
metadata:
  labels:
    app.kubernetes.io/name: detach-handler
    app.kubernetes.io/managed-by: kustomize
  name: machine-sample
spec:
  # TODO(user): Add fields here
