# permissions for end users to view virtualkubeletconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualkubeletconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/part-of: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/managed-by: kustomize
  name: virtualkubeletconfig-viewer-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - virtualkubeletconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - virtualkubeletconfigs/status
  verbs:
  - get
