# permissions for end users to edit virtualkubeletconfigtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualkubeletconfigtemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/part-of: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/managed-by: kustomize
  name: virtualkubeletconfigtemplate-editor-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - virtualkubeletconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - virtualkubeletconfigtemplates/status
  verbs:
  - get
