apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: VirtualKubeletConfig
metadata:
  labels:
    app.kubernetes.io/name: virtualkubeletconfig
    app.kubernetes.io/instance: virtualkubeletconfig-sample
    app.kubernetes.io/part-of: cluster-api-bootstrap-virtual-kubelet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-bootstrap-virtual-kubelet
  name: virtualkubeletconfig-sample
spec:
  # TODO(user): Add fields here
